(cl:defpackage cs_merge_msgs-srv
  (:use )
  (:export
   "GETWORLD"
   "<GETWORLD-REQUEST>"
   "GETWORLD-REQUEST"
   "<GETWORLD-RESPONSE>"
   "GETWORLD-RESPONSE"
   "GETTRANSFORM"
   "<GETTRANSFORM-REQUEST>"
   "GETTRANSFORM-REQUEST"
   "<GETTRANSFORM-RESPONSE>"
   "GETTRANSFORM-RESPONSE"
  ))

