/* Auto-generated by genmsg_cpp for file /home/christian/cs_merge_publication/cs_merge/cs_merge_msgs/srv/getWorld.srv */
#ifndef CS_MERGE_MSGS_SERVICE_GETWORLD_H
#define CS_MERGE_MSGS_SERVICE_GETWORLD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "nav_msgs/OccupancyGrid.h"

namespace cs_merge_msgs
{
template <class ContainerAllocator>
struct getWorldRequest_ {
  typedef getWorldRequest_<ContainerAllocator> Type;

  getWorldRequest_()
  {
  }

  getWorldRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct getWorldRequest
typedef  ::cs_merge_msgs::getWorldRequest_<std::allocator<void> > getWorldRequest;

typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest> getWorldRequestPtr;
typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest const> getWorldRequestConstPtr;



template <class ContainerAllocator>
struct getWorldResponse_ {
  typedef getWorldResponse_<ContainerAllocator> Type;

  getWorldResponse_()
  : world()
  {
  }

  getWorldResponse_(const ContainerAllocator& _alloc)
  : world(_alloc)
  {
  }

  typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _world_type;
   ::nav_msgs::OccupancyGrid_<ContainerAllocator>  world;


  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct getWorldResponse
typedef  ::cs_merge_msgs::getWorldResponse_<std::allocator<void> > getWorldResponse;

typedef boost::shared_ptr< ::cs_merge_msgs::getWorldResponse> getWorldResponsePtr;
typedef boost::shared_ptr< ::cs_merge_msgs::getWorldResponse const> getWorldResponseConstPtr;


struct getWorld
{

typedef getWorldRequest Request;
typedef getWorldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct getWorld
} // namespace cs_merge_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cs_merge_msgs/getWorldRequest";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a57cc86655fe712508fa4becba72db19";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa57cc86655fe7125ULL;
  static const uint64_t static_value2 = 0x08fa4becba72db19ULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cs_merge_msgs/getWorldResponse";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
nav_msgs/OccupancyGrid world\n\
\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct getWorldRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cs_merge_msgs::getWorldResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.world);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct getWorldResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<cs_merge_msgs::getWorld> {
  static const char* value() 
  {
    return "a57cc86655fe712508fa4becba72db19";
  }

  static const char* value(const cs_merge_msgs::getWorld&) { return value(); } 
};

template<>
struct DataType<cs_merge_msgs::getWorld> {
  static const char* value() 
  {
    return "cs_merge_msgs/getWorld";
  }

  static const char* value(const cs_merge_msgs::getWorld&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<cs_merge_msgs::getWorldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a57cc86655fe712508fa4becba72db19";
  }

  static const char* value(const cs_merge_msgs::getWorldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<cs_merge_msgs::getWorldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cs_merge_msgs/getWorld";
  }

  static const char* value(const cs_merge_msgs::getWorldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<cs_merge_msgs::getWorldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a57cc86655fe712508fa4becba72db19";
  }

  static const char* value(const cs_merge_msgs::getWorldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<cs_merge_msgs::getWorldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cs_merge_msgs/getWorld";
  }

  static const char* value(const cs_merge_msgs::getWorldResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CS_MERGE_MSGS_SERVICE_GETWORLD_H

